#!/usr/bin/env lua
-- -*- lua -*-

require("rfsm")
require("fsmdbg")
require("fsmpp")

if arg and #arg == 2 and arg[1] == 'spawn' then
   -- spawn
   fsm_tpl = assert(rfsm.load(arg[2]), "failed to open fsm file " .. arg[2])
   assert(rfsm.is_csta(fsm_tpl), "invalid state machine: not a composite state.")
   fsm_tpl.info = false
   fsm = assert(rfsm.init(fsm_tpl), "error: state machine checking failed.")

   fsm.idle_hook=function () os.execute("sleep 0.1") end
   fsm.dbg = fsmpp.gen_dbgcolor({["STATE_ENTER"]=true, ["STATE_EXIT"]=true,
   				 ["HIBERNATING"]=true, ["EXEC_PATH"]=true,
 				 ["EFFECT"]=true, ["DOO"]=true, ["CHECKING"]=true}),
   -- fsm.dbg=fsmpp.dbgcolor,
   fsmdbg.enable(fsm)
   rfsm.run(fsm)
   -- does not return
   print("stopped")
   os.exit(1)
elseif arg and #arg == 1 and arg[1] == 'cli' then
   -- cli
   c = assert(fsmdbg.cli:new("localhost"))
   function send(...)
      c:sendev(unpack(arg))
   end
   function exit(...)
      c:kill()
   end
   print('rfsm-dbg UI')
   print('commands:')
   print('    send(ev1, ev2, ...)     send events to fsm')
   print('    exit()                  shutdown fsm')
end
