#!/usr/bin/env lua
-- -*- lua -*-
require("rfsmpp")
require("rfsm2uml")
require("rfsm2tree")
require("rfsm")

if arg and #arg < 2 then
   print("usage: rfsmviz [noinit|text|tree|uml|all] <fsm-model-file>")
   os.exit(1)
end

arglt={}
for k,v in ipairs(arg) do
   arglt[v] = true
end

-- last
file = arg[#arg]
outfile = string.gsub(file, "\.%w*$", "")
fsm_tpl = assert(rfsm.load(file), "failed to open fsm file " .. file)
fsm = assert(rfsm.init(fsm_tpl), "error: state machine checking failed.")

-- use initialized or unitialized
if arglt['noinit'] then
   src = fsm_tpl
   fsm_tpl._id = 'root'
else
   src = fsm
end

if arglt['tree'] or arglt['all'] then
   print("generating fsmtree... ", rfsm2tree.rfsm2tree(src, "png", outfile .. "-tree.png"))
end
if arglt['uml'] or arglt['all'] then
   print("generating uml... ", rfsm2uml.rfsm2uml(src, "png", outfile .. "-uml.png"))
end
if arglt['text'] or arglt['all'] then
   print(rfsmpp.fsm2str(src))
end
